# Generated by Django 3.1.4 on 2021-01-10 11:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210110_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='catagory',
            field=models.CharField(choices=[('programming', 'programming'), ('cooking', 'cooking'), ('flaming', 'flaming'), ('cinema', 'cinema'), ('teaching', 'teaching'), ('comedy', 'comedy')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
